// countries.js
export const countries = [
  { code: "US", name: "United States" },
  { code: "IT", name: "Italy" },
  { code: "FR", name: "France" },
  { code: "EG", name: "Egypt" },
  { code: "IN", name: "India" },
  { code: "BR", name: "Brazil" },
  { code: "GB", name: "United Kingdom" },
  { code: "TR", name: "Türkiye" },
  { code: "ES", name: "Spain" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "CO", name: "Colombia" },
  { code: "MX", name: "Mexico" },
  { code: "MA", name: "Morocco" },
  { code: "DE", name: "Germany" },
  { code: "MY", name: "Malaysia" },
  { code: "CA", name: "Canada" },
  { code: "RU", name: "Russia" },
  { code: "ZA", name: "South Africa" },
  { code: "DZ", name: "Algeria" },
  { code: "NG", name: "Nigeria" },
  { code: "NL", name: "Netherlands" },
  { code: "PE", name: "Peru" },
  { code: "SD", name: "Sudan" },
  { code: "PL", name: "Poland" },
  { code: "BE", name: "Belgium" },
  { code: "TN", name: "Tunisia" },
  { code: "ID", name: "Indonesia" },
  { code: "AR", name: "Argentina" },
  { code: "AU", name: "Australia" },
  { code: "CL", name: "Chile" },
  { code: "PH", name: "Philippines" },
  { code: "PT", name: "Portugal" },
  { code: "CN", name: "China" },
  { code: "IL", name: "Israel" },
  { code: "BD", name: "Bangladesh" },
  { code: "CZ", name: "Czechia" },
  { code: "SY", name: "Syria" },
  { code: "YE", name: "Yemen" },
  { code: "OM", name: "Oman" },
  { code: "CH", name: "Switzerland" },
  { code: "LY", name: "Libya" },
  { code: "SE", name: "Sweden" },
  { code: "IR", name: "Iran" },
  { code: "HK", name: "Hong Kong SAR China" },
  { code: "KW", name: "Kuwait" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "JO", name: "Jordan" },
  { code: "BO", name: "Bolivia" },
  { code: "SG", name: "Singapore" },
  { code: "QA", name: "Qatar" },
  { code: "IE", name: "Ireland" },
  { code: "PK", name: "Pakistan" },
  { code: "RO", name: "Romania" },
  { code: "CM", name: "Cameroon" },
  { code: "AT", name: "Austria" },
  { code: "FI", name: "Finland" },
  { code: "DK", name: "Denmark" },
  { code: "LB", name: "Lebanon" },
  { code: "GR", name: "Greece" },
  { code: "HU", name: "Hungary" },
  { code: "GT", name: "Guatemala" },
  { code: "GH", name: "Ghana" },
  { code: "CR", name: "Costa Rica" },
  { code: "VE", name: "Venezuela" },
  { code: "NO", name: "Norway" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "UY", name: "Uruguay" },
  { code: "TH", name: "Thailand" },
  { code: "PA", name: "Panama" },
  { code: "PS", name: "Palestinian Territories" },
  { code: "JP", name: "Japan" },
  { code: "EC", name: "Ecuador" },
  { code: "UA", name: "Ukraine" },
  { code: "BH", name: "Bahrain" },
  { code: "TW", name: "Taiwan" },
  { code: "LC", name: "St. Lucia" },
  { code: "KE", name: "Kenya" },
  { code: "NZ", name: "New Zealand" },
  { code: "VN", name: "Vietnam" },
  { code: "RS", name: "Serbia" },
  { code: "HR", name: "Croatia" },
  { code: "CI", name: "Côte d’Ivoire" },
  { code: "AO", name: "Angola" },
  { code: "BG", name: "Bulgaria" },
  { code: "MU", name: "Mauritius" },
  { code: "KR", name: "South Korea" },
  { code: "AL", name: "Albania" },
  { code: "SK", name: "Slovakia" },
  { code: "SN", name: "Senegal" },
  { code: "AF", name: "Afghanistan" },
  { code: "LK", name: "Sri Lanka" },
  { code: "JM", name: "Jamaica" },
  { code: "SI", name: "Slovenia" },
  { code: "LT", name: "Lithuania" },
  { code: "DO", name: "Dominican Republic" },
  { code: "PR", name: "Puerto Rico" },
  { code: "NP", name: "Nepal" },
  { code: "IQ", name: "Iraq" },
  { code: "BA", name: "Bosnia & Herzegovina" },
  { code: "ET", name: "Ethiopia" },
  { code: "SV", name: "El Salvador" },
  { code: "LV", name: "Latvia" },
  { code: "HN", name: "Honduras" },
  { code: "PY", name: "Paraguay" },
  { code: "BN", name: "Brunei" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "FJ", name: "Fiji" },
  { code: "MG", name: "Madagascar" },
  { code: "IS", name: "Iceland" },
  { code: "KH", name: "Cambodia" },
  { code: "EE", name: "Estonia" },
  { code: "GE", name: "Georgia" },
  { code: "MV", name: "Maldives" },
  { code: "CU", name: "Cuba" },
  { code: "HT", name: "Haiti" },
  { code: "ME", name: "Montenegro" },
  { code: "MW", name: "Malawi" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "BJ", name: "Benin" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "AD", name: "Andorra" },
  { code: "LA", name: "Laos" },
  { code: "SR", name: "Suriname" },
  { code: "LS", name: "Lesotho" },
  { code: "BM", name: "Bermuda" },
  { code: "BT", name: "Bhutan" },
  { code: "MC", name: "Monaco" },
  { code: "PF", name: "French Polynesia" },
  { code: "BZ", name: "Belize" },
  { code: "GD", name: "Grenada" },
  { code: "AG", name: "Antigua & Barbuda" },
  { code: "IM", name: "Isle of Man" },
  { code: "KM", name: "Comoros" },
  { code: "AS", name: "American Samoa" },
  { code: "LI", name: "Liechtenstein" },
  { code: "GL", name: "Greenland" },
  { code: "FO", name: "Faroe Islands" },
  { code: "VC", name: "St. Vincent & Grenadines" },
  { code: "KN", name: "St. Kitts & Nevis" },
  { code: "VU", name: "Vanuatu" },
  { code: "SB", name: "Solomon Islands" },
  { code: "TV", name: "Tuvalu" },
  { code: "ST", name: "São Tomé & Príncipe" },
  { code: "TL", name: "Timor-Leste" },
  { code: "AX", name: "Åland Islands" },
  { code: "AI", name: "Anguilla" },
  { code: "WS", name: "Samoa" },
  { code: "TO", name: "Tonga" },
  { code: "ER", name: "Eritrea" },
  { code: "MH", name: "Marshall Islands" },
  { code: "KI", name: "Kiribati" },
  { code: "PW", name: "Palau" },
  { code: "CK", name: "Cook Islands" },
  { code: "VA", name: "Vatican City" },
  { code: "CW", name: "Curaçao" },
];

export default countries;